name: Despliegue CI/CD a DigitalOcean con GHCR 🚀

on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Iniciar sesión en GHCR (GitHub)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GH_PAT }} 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Construir y subir la Imagen de Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest 
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Sincronizar docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.DIGITAL_OCEAN_USER }}/app_dir" 
          
      - name: Ejecutar despliegue en Droplet de DigitalOcean
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USER }}
          key: ${{ secrets.DIGITAL_OCEAN_KEY }}
          script: |
            APP_DIR=/home/${{ secrets.DIGITAL_OCEAN_USER }}/app_dir
            IMAGE_FULL_TAG=ghcr.io/${{ github.repository }}:latest
            cd $APP_DIR
            
            echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            docker pull $IMAGE_FULL_TAG
            docker compose pull
            docker compose down 
            docker compose up -d
            
            docker image prune -f
            docker logout ghcr.io